# Generated by Django 4.1 on 2022-09-04 19:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0005_alter_scope_article_alter_scope_tag'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Scope',
            new_name='Scopes',
        ),
    ]
