# Generated by Django 4.1 on 2022-09-04 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0007_rename_scopes_scope'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scope',
            name='is_main',
            field=models.BooleanField(default=None, verbose_name='Основной'),
        ),
    ]
