# Generated by Django 4.1 on 2022-09-04 21:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0009_tag_articles'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tag',
            old_name='title',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='tag',
            name='articles',
        ),
    ]
